;;; casual-autoload.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual.el

 (autoload 'casual-init "casual" nil t)
(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual" '("casual-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-agenda.el

 (autoload 'casual-agenda-init "casual-agenda" nil t)
 (autoload 'casual-agenda-tmenu "casual-agenda" nil t)
(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-agenda" '("casual-agenda-setup"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-agenda-settings.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-agenda-settings" '("casual-agenda-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-agenda-utils.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-agenda-utils" '("casual-agenda-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-bibtex.el

 (autoload 'casual-bibtex-init "casual-bibtex" nil t)
 (autoload 'casual-bibtex-tmenu "casual-bibtex" nil t)
(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-bibtex" '("casual-bibtex-setup"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-bibtex-settings.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-bibtex-settings" '("casual-bibtex-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-bibtex-utils.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-bibtex-utils" '("casual-bibtex-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-bookmarks.el

 (autoload 'casual-bookmarks-init "casual-bookmarks" nil t)
 (autoload 'casual-bookmarks-tmenu "casual-bookmarks" nil t)
(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-bookmarks" '("casual-bookmarks-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-bookmarks-settings.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-bookmarks-settings" '("casual-bookmarks-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-bookmarks-utils.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-bookmarks-utils" '("casual-bookmarks-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-calc.el

 (autoload 'casual-calc-init "casual-calc" nil t)
 (autoload 'casual-calc-tmenu "casual-calc" nil t)
(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-calc" '("casual-calc-setup"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-calc--calc.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-calc--calc" '("casual-calc--"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-calc-algebra.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-calc-algebra" '("casual-calc-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-calc-binary.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-calc-binary" '("casual-calc--"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-calc-fileio.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-calc-fileio" '("casual-calc-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-calc-financial.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-calc-financial" '("casual-calc--fin-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-calc-graphics.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-calc-graphics" '("casual-calc--"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-calc-labels.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-calc-labels" '("casual-calc-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-calc-predicates.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-calc-predicates" '("casual-calc-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-calc-random.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-calc-random" '("casual-calc--random-interval-0-to-m"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-calc-settings.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-calc-settings" '("casual-calc-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-calc-stack.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-calc-stack" '("casual-calc-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-calc-time.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-calc-time" '("casual-calc-push-timestamp"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-calc-utils.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-calc-utils" '("casual-calc-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-calc-vector.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-calc-vector" '("casual-calc--histogram"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-calendar.el

 (autoload 'casual-calendar-init "casual-calendar" nil t)
 (autoload 'casual-calendar "casual-calendar" nil t)
 (autoload 'casual-calendar-tmenu "casual-calendar" nil t)
(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-calendar" '("casual-calendar-setup"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-calendar-constants.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-calendar-constants" '("casual-calendar-unicode-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-calendar-settings.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-calendar-settings" '("casual-calendar-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-compile.el

 (autoload 'casual-compile-init "casual-compile" nil t)
 (autoload 'casual-compile-tmenu "casual-compile" nil t)
(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-compile" '("casual-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-compile-settings.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-compile-settings" '("casual-compile-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-compile-utils.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-compile-utils" '("casual-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-css.el

 (autoload 'casual-css-init "casual-css" nil t)
 (autoload 'casual-css-tmenu "casual-css" nil t)
(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-css" '("casual-css-setup"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-css-settings.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-css-settings" '("casual-css-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-css-utils.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-css-utils" '("casual-css-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-csv.el

 (autoload 'casual-csv-init "casual-csv" nil t)
 (autoload 'casual-csv-tmenu "casual-csv" nil t)
(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-csv" '("casual-csv-setup"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-csv-settings.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-csv-settings" '("casual-csv-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-csv-utils.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-csv-utils" '("casual-csv-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-dired.el

 (autoload 'casual-dired-init "casual-dired" nil t)
 (autoload 'casual-dired-tmenu "casual-dired" nil t)
(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-dired" '("casual-dired-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-dired-settings.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-dired-settings" '("casual-dired-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-dired-sort-by.el

 (autoload 'casual-dired-sort-by-tmenu "casual-dired-sort-by" nil t)
(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-dired-sort-by" '("casual-dired--"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-dired-utils.el

 (autoload 'casual-dired-utils-tmenu "casual-dired-utils" nil t)
 (autoload 'casual-dired-search-replace-tmenu "casual-dired-utils" nil t)
 (autoload 'casual-dired-elisp-tmenu "casual-dired-utils" nil t)
 (autoload 'casual-dired-link-tmenu "casual-dired-utils" nil t)
(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-dired-utils" '("casual-dired-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-dired-variables.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-dired-variables" '("casual-dired-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-ediff.el

 (autoload 'casual-ediff-init "casual-ediff" nil t)
 (autoload 'casual-ediff-tmenu "casual-ediff" nil t)
 (autoload 'casual-ediff-install "casual-ediff" nil t)
 (autoload 'casual-ediff-uninstall "casual-ediff" nil t)
(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-ediff" '("casual-ediff-setup"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-ediff-settings.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-ediff-settings" '("casual-ediff-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-ediff-utils.el

 (autoload 'casual-ediff-revision "casual-ediff-utils" nil t)
(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-ediff-utils" '("casual-ediff-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-editkit.el

 (autoload 'casual-editkit-init "casual-editkit" nil t)
 (autoload 'casual-editkit-main-tmenu "casual-editkit" nil t)


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-editkit-constants.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-editkit-constants" '("casual-editkit-unicode-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-editkit-settings.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-editkit-settings" '("casual-editkit-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-editkit-utils.el

 (autoload 'casual-editkit-open-tmenu "casual-editkit-utils" nil t)
 (autoload 'casual-editkit-project-tmenu "casual-editkit-utils" nil t)
 (autoload 'casual-editkit-edit-tmenu "casual-editkit-utils" nil t)
 (autoload 'casual-editkit-emoji-symbols-tmenu "casual-editkit-utils" nil t)
 (autoload 'casual-editkit-mark-tmenu "casual-editkit-utils" nil t)
 (autoload 'casual-editkit-copy-tmenu "casual-editkit-utils" nil t)
 (autoload 'casual-editkit-kill-tmenu "casual-editkit-utils" nil t)
 (autoload 'casual-editkit-sort-tmenu "casual-editkit-utils" nil t)
 (autoload 'casual-editkit-transpose-tmenu "casual-editkit-utils" nil t)
 (autoload 'casual-editkit-delete-tmenu "casual-editkit-utils" nil t)
 (autoload 'casual-editkit-move-text-tmenu "casual-editkit-utils" nil t)
 (autoload 'casual-editkit-windows-tmenu "casual-editkit-utils" nil t)
 (autoload 'casual-editkit-windows-delete-tmenu "casual-editkit-utils" nil t)
 (autoload 'casual-editkit-bookmarks-tmenu "casual-editkit-utils" nil t)
 (autoload 'casual-editkit-search-tmenu "casual-editkit-utils" nil t)
 (autoload 'casual-editkit-tools-tmenu "casual-editkit-utils" nil t)
 (autoload 'casual-editkit-registers-tmenu "casual-editkit-utils" nil t)
 (autoload 'casual-editkit-rectangle-tmenu "casual-editkit-utils" nil t)
 (autoload 'casual-editkit-transform-text-tmenu "casual-editkit-utils" nil t)
 (autoload 'casual-editkit-macro-tmenu "casual-editkit-utils" nil t)
 (autoload 'casual-editkit-reformat-tmenu "casual-editkit-utils" nil t)
 (autoload 'casual-editkit-narrow-tmenu "casual-editkit-utils" nil t)
(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-editkit-utils" '("casual-editkit-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-elisp.el

 (autoload 'casual-elisp-init "casual-elisp" nil t)
 (autoload 'casual-elisp-tmenu "casual-elisp" nil t)
(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-elisp" '("casual-elisp-setup"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-elisp-settings.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-elisp-settings" '("casual-elisp-about"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-elisp-utils.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-elisp-utils" '("casual-elisp-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-eshell.el

 (autoload 'casual-eshell-init "casual-eshell" nil t)
 (autoload 'casual-eshell-tmenu "casual-eshell" nil t)
(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-eshell" '("casual-eshell-setup"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-eshell-settings.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-eshell-settings" '("casual-eshell-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-eshell-utils.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-eshell-utils" '("casual-eshell-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-eww.el

 (autoload 'casual-eww-init "casual-eww" nil t)
 (autoload 'casual-eww-tmenu "casual-eww" nil t)
 (autoload 'casual-eww-bookmarks-tmenu "casual-eww" nil t)
(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-eww" '("casual-eww-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-eww-settings.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-eww-settings" '("casual-eww-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-eww-utils.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-eww-utils" '("casual-eww-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-help.el

 (autoload 'casual-help-init "casual-help" nil t)
 (autoload 'casual-help-tmenu "casual-help" nil t)
(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-help" '("casual-help-setup"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-help-settings.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-help-settings" '("casual-help-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-help-utils.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-help-utils" '("casual-help-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-html.el

 (autoload 'casual-html-init "casual-html" nil t)
 (autoload 'casual-html-tmenu "casual-html" nil t)
 (autoload 'casual-html-tags-tmenu "casual-html" nil t)
(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-html" '("casual-html-setup"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-html-settings.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-html-settings" '("casual-html-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-html-utils.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-html-utils" '("casual-html-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-ibuffer.el

 (autoload 'casual-ibuffer-init "casual-ibuffer" nil t)
 (autoload 'casual-ibuffer-tmenu "casual-ibuffer" nil t)
 (autoload 'casual-ibuffer-sortby-tmenu "casual-ibuffer" nil t)
(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-ibuffer" '("casual-ibuffer-setup"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-ibuffer-filter.el

 (autoload 'casual-ibuffer-filter-tmenu "casual-ibuffer-filter" nil t)
(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-ibuffer-filter" '("casual-ibuffer-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-ibuffer-settings.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-ibuffer-settings" '("casual-ibuffer-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-ibuffer-utils.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-ibuffer-utils" '("casual-ibuffer-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-image.el

 (autoload 'casual-image-init "casual-image" nil t)
 (autoload 'casual-image-tmenu "casual-image" nil t)
(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-image" '("casual-image-setup"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-image-settings.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-image-settings" '("casual-image--customize-group"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-image-utils.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-image-utils" '("casual-image-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-info.el

 (autoload 'casual-info-init "casual-info" nil t)
 (autoload 'casual-info-tmenu "casual-info" nil t)
(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-info" '("casual-info-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-info-settings.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-info-settings" '("casual-info-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-info-utils.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-info-utils" '("casual-info-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-info-variables.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-info-variables" '("casual-info-use-unicode-symbols"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-isearch.el

 (autoload 'casual-isearch-init "casual-isearch" nil t)
 (autoload 'casual-isearch-tmenu "casual-isearch" nil t)
(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-isearch" '("casual-isearch-setup"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-isearch-settings.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-isearch-settings" '("casual-isearch-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-isearch-utils.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-isearch-utils" '("casual-isearch-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-ispell.el

 (autoload 'casual-ispell-tmenu "casual-ispell" nil t)


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-ispell-settings.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-ispell-settings" '("casual-ispell-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-ispell-utils.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-ispell-utils" '("casual-ispell-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-lib.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-lib" '("casual-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-make.el

 (autoload 'casual-make-init "casual-make" nil t)
 (autoload 'casual-make-tmenu "casual-make" nil t)
(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-make" '("casual-make-setup"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-make-settings.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-make-settings" '("casual-make-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-make-utils.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-make-utils" '("casual-make-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-man.el

 (autoload 'casual-man-init "casual-man" nil t)
 (autoload 'casual-man-tmenu "casual-man" nil t)
(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-man" '("casual-man-setup"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-man-settings.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-man-settings" '("casual-man-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-man-utils.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-man-utils" '("casual-man-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-org.el

 (autoload 'casual-org-init "casual-org" nil t)
 (autoload 'casual-org-tmenu "casual-org" nil t)
 (autoload 'casual-org-table-fedit-tmenu "casual-org" nil t)
(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-org" '("casual-org-setup"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-org-settings.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-org-settings" '("casual-org-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-org-utils.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-org-utils" '("casual-org-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-re-builder.el

 (autoload 'casual-re-builder-init "casual-re-builder" nil t)
 (autoload 'casual-re-builder-tmenu "casual-re-builder" nil t)
(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-re-builder" '("casual-re-builder-setup"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-re-builder-settings.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-re-builder-settings" '("casual-re-builder-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-re-builder-utils.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-re-builder-utils" '("casual-re"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-timezone.el

 (autoload 'casual-timezone-tmenu "casual-timezone" nil t)


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-timezone-settings.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-timezone-settings" '("casual-timezone-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-timezone-utils.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-timezone-utils" '("casual-timezone-"))


;;; Generated autoloads from ccinit.el

(register-definition-prefixes "ccinit" '("cc--workplace-initialized" "cc/"))


;;; Generated autoloads from cclisp.el

(register-definition-prefixes "cclisp" '("arrayify" "cc-speech-" "cc/" "datestamp" "dm/copy-as-rtf" "ia-writer-timestamp-to-org" "jxa-repl" "melpa-package-status" "music" "node-repl" "s-replace" "scroll-one-line-" "status-report-dev7" "swift-repl" "system-move-file-to-trash" "weather" "year"))


;;; Generated autoloads from cc-emacs-lisp-mode.el

(register-definition-prefixes "cc-emacs-lisp-mode" '("cc/" "edebug-mode-p" "emacsql-"))


;;; Generated autoloads from cc-eww-mode.el

(register-definition-prefixes "cc-eww-mode" '("cc/eww-"))


;;; Generated autoloads from ../../Projects/elisp/casual/lisp/casual-calendar-utils.el

(register-definition-prefixes "../../Projects/elisp/casual/lisp/casual-calendar-utils" '("casual-calendar-add-extra-keybindings"))

;;; End of scraped data

(provide 'casual-autoload)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; casual-autoload.el ends here
